DROP TABLE IF EXISTS `t_sku_day_a`;
CREATE TABLE `t_sku_day_a` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键自增长',
  `store_id` varchar(10) NOT NULL COMMENT '店号',
  `sku_no` varchar(20) NOT NULL COMMENT '商品编号',
  `company_code` varchar(20) DEFAULT NULL COMMENT '公司编号',
  `company_group_code` varchar(20) DEFAULT NULL COMMENT '运营中心编号',
  `check_date` date DEFAULT NULL COMMENT '账表日',
  `settle_date` date DEFAULT NULL COMMENT '结账日',
  `sale_count` int(11) DEFAULT NULL COMMENT '销售数量',
  `sale_cost` decimal(20,8) DEFAULT NULL COMMENT '销售成本',
  `sale_cost_tax` decimal(20,8) DEFAULT NULL COMMENT '销售成本税额',
  `sale_amount` decimal(20,8) DEFAULT NULL COMMENT '销售金额',
  `sale_tax` decimal(20,8) DEFAULT NULL COMMENT '销售税额',
  `receive_count` int(11) DEFAULT NULL COMMENT '收货数量',
  `receive_cost` decimal(20,8) DEFAULT NULL COMMENT '收货成本',
  `receive_cost_tax` decimal(20,8) DEFAULT NULL COMMENT '收货成本税额',
  `receive_amount` decimal(20,8) DEFAULT NULL COMMENT '收货金额',
  `receive_tax` decimal(20,8) DEFAULT NULL COMMENT '收货税额',
  `return_count` int(11) DEFAULT NULL COMMENT '退货数量',
  `return_cost` decimal(20,8) DEFAULT NULL COMMENT '退货成本',
  `return_cost_tax` decimal(20,8) DEFAULT NULL COMMENT '退货成本税额',
  `return_amount` decimal(20,8) DEFAULT NULL COMMENT '退货金额',
  `return_tax` decimal(20,8) DEFAULT NULL COMMENT '退货税额',
  `trans_out_count` int(11) DEFAULT NULL COMMENT '转出数量',
  `trans_out_cost` decimal(20,8) DEFAULT NULL COMMENT '转出成本金额',
  `trans_out_cost_tax` decimal(20,8) DEFAULT NULL COMMENT '转出成本税额',
  `trans_out_amount` decimal(20,8) DEFAULT NULL COMMENT '转出金额',
  `trans_out_tax` decimal(20,8) DEFAULT NULL COMMENT '转出税额',
  `trans_in_count` int(11) DEFAULT NULL COMMENT '转出数量',
  `trans_in_cost` decimal(20,8) DEFAULT NULL COMMENT '转入成本金额',
  `trans_in_cost_tax` decimal(20,8) DEFAULT NULL COMMENT '转入成本税额',
  `trans_in_amount` decimal(20,8) DEFAULT NULL COMMENT '转入金额',
  `trans_in_tax` decimal(20,8) DEFAULT NULL COMMENT '转入税额',
  `stock_count` int(11) DEFAULT NULL COMMENT '盘实数量',
  `adjust_amount` decimal(20,8) DEFAULT NULL COMMENT '调整金额',
  `adjust_tax` decimal(20,8) DEFAULT NULL COMMENT '调整税额',
  `scrap_count` int(11) DEFAULT NULL COMMENT '报废数量',
  `scrap_amount` decimal(20,8) DEFAULT NULL COMMENT '报废金额',
  `scrap_tax` decimal(20,8) DEFAULT NULL COMMENT '报废税额',
  `output_tax` decimal(20,8) DEFAULT NULL COMMENT '销项税率',
  `selling_price` decimal(20,8) DEFAULT NULL COMMENT '门店售价(价格体系)',
  `logistics_output_tax` decimal(20,8) DEFAULT NULL COMMENT '物流销项税%',
  `inventory_account` int(11) DEFAULT NULL COMMENT '口座类型,1:快速饮料(quick_drink);2:茶叶蛋(tea_eggs);3:香烟(cigarette);4:酒(wine);5:应税16%(taxable_sixteen_percent);6:应税10%(taxable_ten_percent);7:应税3%(taxable_three_percent);8:应税0%(taxable_zero_percent)',
  `creator_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_store_sku_date` (`store_id`,`sku_no`,`check_date`)
);

DROP TABLE IF EXISTS `t_sku_day_b`;
CREATE TABLE `t_sku_day_b` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键自增长',
  `store_id` varchar(10) NOT NULL COMMENT '店号',
  `sku_no` varchar(20) NOT NULL COMMENT '商品编号',
  `company_code` varchar(20) DEFAULT NULL COMMENT '公司编号',
  `company_group_code` varchar(20) DEFAULT NULL COMMENT '运营中心编号',
  `check_date` date DEFAULT NULL COMMENT '账表日',
  `settle_date` date DEFAULT NULL COMMENT '结账日',
  `first_count` int(11) DEFAULT NULL COMMENT '期初数量',
  `first_cost` decimal(20,8) DEFAULT NULL COMMENT '期初成本',
  `first_cost_tax` decimal(20,8) DEFAULT NULL COMMENT '期初成本税额',
  `first_cost_avg` decimal(20,8) DEFAULT NULL COMMENT '期初加权平均成本(单价)',
  `first_amount` decimal(20,8) DEFAULT NULL COMMENT '期初金额',
  `first_tax` decimal(20,8) DEFAULT NULL COMMENT '期初税额',
  `scrap_cost` decimal(20,8) DEFAULT NULL COMMENT '报废成本',
  `scrap_cost_tax` decimal(20,8) DEFAULT NULL COMMENT '报废成本税额',
  `change_count` int(11) DEFAULT NULL COMMENT '变价数量',
  `change_amount` decimal(20,8) DEFAULT NULL COMMENT '变价金额',
  `change_tax` decimal(20,8) DEFAULT NULL COMMENT '变价税额',
  `adjust_cost` decimal(20,8) DEFAULT NULL COMMENT '调整成本金额',
  `adjust_cost_tax` decimal(20,8) DEFAULT NULL COMMENT '调整成本税额',
  `stock_count` int(11) DEFAULT NULL COMMENT '盘实数量',
  `stock_win_count` int(11) DEFAULT NULL COMMENT '盘盈亏数量',
  `stock_cost` decimal(20,8) DEFAULT NULL COMMENT '盘盈亏成本金额',
  `stock_cost_tax` decimal(20,8) DEFAULT NULL COMMENT '盘盈亏成本税额',
  `stock_amount` decimal(20,8) DEFAULT NULL COMMENT '盘盈亏金额',
  `stock_tax` decimal(20,8) DEFAULT NULL COMMENT '盘盈亏税额',
  `final_count` int(11) DEFAULT NULL COMMENT '期末数量',
  `final_cost` decimal(20,8) DEFAULT NULL COMMENT '期末成本',
  `final_cost_tax` decimal(20,8) DEFAULT NULL COMMENT '期末成本税额',
  `final_cost_avg` decimal(20,8) DEFAULT NULL COMMENT '期末加权平均成本(单价)',
  `final_amount` decimal(20,8) DEFAULT NULL COMMENT '期末金额',
  `final_tax` decimal(20,8) DEFAULT NULL COMMENT '期末税额',
  `selling_price` decimal(20,8) DEFAULT NULL COMMENT '门店售价(价格体系)',
  `output_tax` decimal(20,8) DEFAULT NULL COMMENT '销项税率',
  `logistics_output_tax` decimal(20,8) DEFAULT NULL COMMENT '物流销项税%',
  `inventory_account` int(11) DEFAULT NULL COMMENT '口座类型,1:快速饮料(quick_drink);2:茶叶蛋(tea_eggs);3:香烟(cigarette);4:酒(wine);5:应税16%(taxable_sixteen_percent);6:应税10%(taxable_ten_percent);7:应税3%(taxable_three_percent);8:应税0%(taxable_zero_percent)',
  `banlance_amount` decimal(20,8) DEFAULT NULL COMMENT '差额平衡金额',
  `spare_amount` decimal(20,8) DEFAULT NULL COMMENT '备用字段',
  `creator_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_store_sku_date_b` (`store_id`,`sku_no`,`check_date`)
);


DROP TABLE IF EXISTS `test`;
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键自增长',
  `name`varchar(20) NOT NULL COMMENT '姓名',
  `age`varchar(20) NOT NULL COMMENT '年龄',
  PRIMARY KEY (`id`),
);

INSERT into test set name = 'maple' , age = '20';
INSERT into test set name = 'struy' , age = '21';
INSERT into test set name = 'ever' , age = '22';

